apiVersion: apps/v1
kind: Deployment
metadata:
  name: netperf-server
  labels:
    app.kubernetes.io/name: netperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: netperf-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netperf-server
    spec:
      containers:
      - name: netperf-server
        image: pete911/netperf:latest
        imagePullPolicy: IfNotPresent
        command: ["netserver", "-D"]
        ports:
        - containerPort: 12865
          name: server
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netperf-client
  labels:
    app.kubernetes.io/name: netperf-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: netperf-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netperf-client
    spec:
      containers:
      - name: netperf-client
        image: pete911/netperf:latest
        imagePullPolicy: IfNotPresent
        command:
          - sleep
          - "3600"
